language: php

before_script:
 - composer self-update
 - composer install --prefer-source --no-interaction --dev

script:
 - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

matrix:
 include: 
  - os: linux
    dist: trusty
    php: 5.4
  - os: linux
    dist: trusty
    php: 5.5
  - os: linux
    dist: xenial
    php: 5.6
  - os: linux
    dist: xenial
    php: 7.0
  - os: linux
    dist: xenial
    php: 7.1
  - os: linux
    dist: xenial
    php: 7.2
  - os: linux
    dist: xenial
    php: 7.3
#  - os: linux
#    dist: bionic
#    php: 7.4
  - os: linux
    dist: bionic
    php: nightly
 allow_failures:
  - php: hhvm
  - php: nightly
